version: "3.1"

services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  redis:
    image: redis
    ports:
      - "6379:6379"

  machinery:
    image: krullie/machinery-example
    command: worker
    depends_on:
      - jaeger
      - redis
    environment:
      BROKER: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      JAEGER_HOST: jaeger:6831